name: CI
on: [push]
jobs:
  standard-checks:
    name: Lint and Test
    runs-on: windows-2016

    steps:
      - run: node -v
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci
      - name: Run ESlint
        run: npm run ci:lint
      - name: Run Test
        run: npm run ci:test
